blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('blog/detail/', views.BlogDetailView.as_view(), name='blog_detail'),
]

personal_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View


class HomePage(TemplateView):
    template_name = 'blog/index.html'


class BlogDetailView(TemplateView):
    template_name = 'blog/blog_detail.html'


class AboutView(TemplateView):
    template_name = 'blog/about.html'

templates/blog/about.html
{% extends 'blog/base.html' %}

{% load static %}

{% block content %}
<div class="main-wrapper">
    <article class="about-section py-5">
        <div class="container">
            <h2 class="title mb-3">About Me</h2>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
                Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis,
                ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo,
                fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis
                vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus
                elementum semper nisi. Aenean vulputate eleifend tellus. </p>
            <figure><img class="img-fluid" src="{% static 'images/about-me.jpg' %}" alt="image"></figure>
            <h5 class="mt-5">About The Blog</h5>
            <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu,
                consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.
                Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi
                vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus
                eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam
                nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus.
                Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros
                faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed
                consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce
                vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus.</p>
            <h5 class="mt-5">My Skills and Experiences</h5>
            <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu,
                consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.
                Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi
                vel augue. Curabitur ullamcorper ultricies nisi.</p>
            <h5 class="mt-5">Side Projects</h5>
            <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu,
                consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.
                Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi
                vel augue. Curabitur ullamcorper ultricies nisi.</p>
        </div>
    </article>
    <!--//about-section-->
    {% include 'blog/partials/subscribe.html' %}
</div>
<!--//main-wrapper-->
{% include 'blog/partials/choose_theme.html' %}
{% endblock content %}

templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Ramesh Pradhan {% block title %}{% endblock title %}</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <!-- FontAwesome JS-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js"
        integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7"
        crossorigin="anonymous"></script>

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'css/theme-4.css' %}">
    {% block extra_styles %}{% endblock extra_styles %}
</head>

<body>
    {% include 'blog/partials/header.html' %}
    {% block content %}{% endblock content %}
    <!-- Javascript -->
    <script src="{% static 'plugins/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'plugins/popper.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
    <script src="{% static 'js/demo/style-switcher.js' %}"></script>
    {% block extra_scripts %}{% endblock extra_scripts %}
</body>

</html>

templates/blog/blog_detail.html
{% extends 'blog/base.html' %}

{% load static %}

{% block content %}
<div class="main-wrapper">
    <article class="blog-post px-3 py-5 p-md-5">
        <div class="container">
            <header class="blog-post-header">
                <h2 class="title mb-2">Why Every Developer Should Have A Blog</h2>
                <div class="meta mb-3"><span class="date">Published 3 months ago</span><span class="time">5 min
                        read</span><span class="comment"><a href="#">4 comments</a></span></div>
            </header>

            <div class="blog-post-body">
                <figure class="blog-banner">
                    <a href="https://made4dev.com"><img class="img-fluid" src="{% static 'images/rafting.jpg' %}"
                            alt="image"></a>
                    <figcaption class="mt-2 text-center image-caption">
                        Image Credit:
                        <a href="https://made4dev.com?ref=devblog" target="_blank">
                            made4dev.com (Premium Programming T-shirts)
                        </a>
                    </figcaption>
                </figure>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean
                    massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
                    quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
                    Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut,
                    imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.
                    Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula,
                    porttitor eu, consequat vitae, eleifend ac, enim. </p>

                <h3 class="mt-5 mb-3">Code Block Example</h3>
                <p>You can get more info at <a href="https://highlightjs.org/"
                        target="_blank">https://highlightjs.org/</a>. Lorem ipsum dolor sit amet, consectetuer
                    adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et
                    magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque
                    eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet
                    nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam
                    dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.
                    Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac,
                    enim. </p>
                <pre>
                    <code>
function $initHighlight(block, cls) {
try {
if (cls.search(/\bno\-highlight\b/) != -1)
  return process(block, true, 0x0F) +
         ` class="${cls}"`;
} catch (e) {
/* handle exception */
}
for (var i = 0 / 2; i < classes.length; i++) {
if (checkCondition(classes[i]) === undefined)
  console.log('undefined');
}
}

export  $initHighlight;
                    </code>
                </pre>
                <h3 class="mt-5 mb-3">Typography</h3>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean
                    massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                <h5 class="my-3">Bullet Points:</h5>
                <ul class="mb-5">
                    <li class="mb-2">Lorem ipsum dolor sit amet consectetuer.</li>
                    <li class="mb-2">Aenean commodo ligula eget dolor.</li>
                    <li class="mb-2">Aenean massa cum sociis natoque penatibus.</li>
                </ul>
                <ol class="mb-5">
                    <li class="mb-2">Lorem ipsum dolor sit amet consectetuer.</li>
                    <li class="mb-2">Aenean commodo ligula eget dolor.</li>
                    <li class="mb-2">Aenean massa cum sociis natoque penatibus.</li>
                </ol>
                <h5 class="my-3">Quote Example:</h5>
                <blockquote class="blockquote m-lg-5 py-3 pl-4 px-lg-5">
                    <p class="mb-2">You might not think that programmers are artists, but programming is an extremely
                        creative profession. It's logic-based creativity.</p>
                    <footer class="blockquote-footer">John Romero</footer>
                </blockquote>

                <h5 class="my-3">Table Example:</h5>
                <table class="table table-striped my-5">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">First</th>
                            <th scope="col">Last</th>
                            <th scope="col">Handle</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Jacob</td>
                            <td>Thornton</td>
                            <td>@fat</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Larry</td>
                            <td>the Bird</td>
                            <td>@twitter</td>
                        </tr>
                    </tbody>
                </table>

                <h5 class="mb-3">Embed A Tweet:</h5>
                <blockquote class="twitter-tweet" data-lang="en">
                    <p lang="en" dir="ltr">1969:<br>-what&#39;re you doing with that 2KB of RAM?<br>-sending people to
                        the moon<br><br>2017:<br>-what&#39;re you doing with that 1.5GB of RAM?<br>-running Slack</p>
                    &mdash; I Am Devloper (@iamdevloper) <a
                        href="https://twitter.com/iamdevloper/status/926458505355235328?ref_src=twsrc%5Etfw">November 3,
                        2017</a>
                </blockquote>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

                <h3 class="mt-5 mb-3">Video Example</h3>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean
                    massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
                    quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. </p>

                <div class="embed-responsive embed-responsive-16by9">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/hnCmSXCZEpU" frameborder="0"
                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
                </div>

            </div>

            <nav class="blog-nav nav nav-justified my-5">
                <a class="nav-link-prev nav-item nav-link rounded-left" href="index.html">Previous<i
                        class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
                <a class="nav-link-next nav-item nav-link rounded-right" href="blog-list.html">Next<i
                        class="arrow-next fas fa-long-arrow-alt-right"></i></a>
            </nav>
            {% include 'blog/partials/disqus_comment.html' %}
        </div>
        <!--//container-->
    </article>
</div>
<!--//main-wrapper-->
{% include 'blog/partials/choose_theme.html' %}
{% endblock content %}

templates/blog/blog_list.html
{% load static %}

<section class="blog-list px-3 py-5 p-md-5">
    <div class="container">
        <div class="item mb-5">
            <div class="media">
                <img class="mr-3 img-fluid post-thumb d-none d-md-flex"
                    src="{% static 'images/blog/blog-post-thumb-1.jpg' %}" alt="image">
                <div class="media-body">
                    <h3 class="title mb-1"><a href="{% url 'blog:blog_detail' %}">Why Every Developer Should Have A
                            Blog</a>
                    </h3>
                    <div class="meta mb-1"><span class="date">Published 2 days ago</span><span class="time">5
                            min read</span><span class="comment"><a href="#">8 comments</a></span></div>
                    <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
                        ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient
                        montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                    <a class="more-link" href="blog-post.html">Read more &rarr;</a>
                </div>
                <!--//media-body-->
            </div>
            <!--//media-->
        </div>
        <nav class="blog-nav nav nav-justified my-5">
            <a class="nav-link-prev nav-item nav-link d-none rounded-left" href="#">Previous<i
                    class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
            <a class="nav-link-next nav-item nav-link rounded" href="blog-list.html">Next<i
                    class="arrow-next fas fa-long-arrow-alt-right"></i></a>
        </nav>
    </div>
</section>

templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="main-wrapper">
    {% include 'blog/partials/subscribe.html' %}
    {% include 'blog/blog_list.html' %}
</div>
<!--//main-wrapper-->
{% include 'blog/partials/choose_theme.html' %}
{% endblock content %}

templates/blog/partials/choose_theme.html
{% load static %}

<!-- *****CONFIGURE STYLE (REMOVE ON YOUR PRODUCTION SITE)****** -->
<div id="config-panel" class="config-panel d-none d-lg-block">
    <div class="panel-inner">
        <a id="config-trigger" class="config-trigger config-panel-hide text-center" href="#"><i
                class="fas fa-cog fa-spin mx-auto" data-fa-transform="down-6"></i></a>
        <h5 class="panel-title">Choose Colour</h5>
        <ul id="color-options" class="list-inline mb-0">
            <li class="theme-1 list-inline-item">
                <a data-style="{% static 'css/theme-1.css' %}" href="#"></a>
            </li>
            <li class="theme-2 list-inline-item">
                <a data-style="{% static 'css/theme-2.css' %}" href="#"></a>
            </li>
            <li class="theme-3 list-inline-item">
                <a data-style="{% static 'css/theme-3.css' %}" href="#"></a>
            </li>
            <li class="theme-4 active list-inline-item">
                <a data-style="{% static 'css/theme-4.css' %}" href="#"></a>
            </li>
            <li class="theme-5 list-inline-item">
                <a data-style="{% static 'css/theme-5.css' %}" href="#"></a>
            </li>
            <li class="theme-6 list-inline-item">
                <a data-style="{% static 'css/theme-6.css' %}" href="#"></a>
            </li>
            <li class="theme-7 list-inline-item">
                <a data-style="{% static 'css/theme-7.css' %}" href="#"></a>
            </li>
            <li class="theme-8 list-inline-item">
                <a data-style="{% static 'css/theme-8.css' %}" href="#"></a>
            </li>
        </ul>
        <a id="config-close" class="close" href="#"><i class="fa fa-times-circle"></i></a>
    </div>
    <!--//panel-inner-->
</div>
<!--//configure-panel-->

templates/blog/partials/disqus_comment.html
{% load static %}

<div class="blog-comments-section">
    <div id="disqus_thread"></div>
    <script>
        /**
         *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT 
         *  THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR 
         *  PLATFORM OR CMS.
         *  
         *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: 
         *  https://disqus.com/admin/universalcode/#configuration-variables
         */
        /*
        var disqus_config = function () {
            // Replace PAGE_URL with your page's canonical URL variable
            this.page.url = PAGE_URL;  
            
            // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            this.page.identifier = PAGE_IDENTIFIER; 
        };
        */

        (function () {  // REQUIRED CONFIGURATION VARIABLE: EDIT THE SHORTNAME BELOW
            var d = document, s = d.createElement('script');

            // IMPORTANT: Replace 3wmthemes with your forum shortname!
            s.src = 'https://3wmthemes.disqus.com/embed.js';

            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>
        Please enable JavaScript to view the
        <a href="https://disqus.com/?ref_noscript" rel="nofollow">
            comments powered by Disqus.
        </a>
    </noscript>
</div>
<!--//blog-comments-section-->

templates/blog/partials/footer.html
<footer class="footer text-center py-2 theme-bg-dark">
    <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
    <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a
            href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
</footer>

templates/blog/partials/header.html
{% load static %}

<header class="header text-center">
    <h1 class="blog-name pt-lg-4 mb-0"><a href="{% url 'blog:home' %}">Ramesh's Blog</a></h1>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
            aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navigation" class="collapse navbar-collapse flex-column">
            <div class="profile-section pt-3 pt-lg-0">
                <img class="profile-image mb-3 rounded-circle mx-auto"
                    src="{% static 'images/blog_profile_image.jpg' %}" alt="image">

                <div class="bio mb-3">Hi, my name is Ramesh Pradhan. I am a Python/Django developer and a Tech
                    Enthusiast.<br>
                    <a href="{% url 'blog:about' %}">Find out more about me</a>
                </div>
                <!--//bio-->
                <ul class="social-list list-inline py-3 mx-auto">
                    <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                </ul>
                <!--//social-list-->
                <hr>
            </div>
            <!--//profile-section-->
            <ul class="navbar-nav flex-column text-left">
                {% url 'blog:home' as home_page %}
                <li class="nav-item {% if request.path == home_page %}active{% endif %}">
                    <a class="nav-link" href="{% url 'blog:home' %}"><i class="fas fa-home fa-fw mr-2"></i>Blog Home
                        <span class="sr-only">(current)</span></a>
                </li>
                {% url 'blog:about' as about_page %}
                <li class="nav-item {% if request.path == about_page %}active{% endif %}">
                    <a class="nav-link" href="{% url 'blog:about' %}"><i class="fas fa-user fa-fw mr-2"></i>About Me</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

templates/blog/partials/subscribe.html
<section class="cta-section theme-bg-light py-5">
    <div class="container text-center">
        <h2 class="heading">DevBlog - A Blog Template Made For Developers</h2>
        <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
        <form class="signup-form form-inline justify-content-center pt-3">
            <div class="form-group">
                <label class="sr-only" for="semail">Your email</label>
                <input type="email" id="semail" name="semail1" class="form-control mr-md-1 semail"
                    placeholder="Enter email">
            </div>
            <button type="submit" class="btn btn-primary">Subscribe</button>
        </form>
    </div>
    <!--//container-->
</section>